name: Update README with WakaTime activity

on:
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROFILE_VIEWS: False
          SHOW_UPDATED_DATE: False
          SHOW_EDITORS: False
          SHOW_LOC_CHART: False
          SHOW_TIMEZONE: False
          SHOW_PROJECTS: False
          SHOW_OS: False
          SHOW_TOTAL_CODE_TIME: False
